### ISSUE TITLE
这个闭包的例子有问题

### ISSUE THREAD

**Issue by txf626** [Baidu-Post-Bar-Python/CodeForBegginers#1]
```python
class Garbage:
    id = 0

    def __init__(self):
        Garbage.id += 1
        self.id = Garbage.id


g1 = Garbage()
print(g1.id)  # 1
del g1
g2 = Garbage()
print(g2.id)  # 2
```
id 是类变量, 当第一个类的实例化对象是修改id后,后面的类实例化对象的id会变成修改后的,所以它不是闭包导致的原因.
```python
class A(object):
    id = 0

    def __init__(self):
        A.id += 1


a1 = A()
print(a1.id)  # 第一次输出化 0+1

a2 = A()
print(a2.id)  # 第二次初始化 1+1

```

**Comment by DarrenDanielDay** [comment]
首先感谢您提出了issue。

可能是注释写的还不够详细，导致您对此例子产生了误解，是笔者的疏漏。
关于您提出的问题，笔者做出如下两点解释：

第一，Garbage.id的意图是统计Garbage实例化的次数。而`self.id = Garbage.id`的作用则是将实例属性`id`赋值为当前的`Garbage.id`。如果将代码以更清楚的语义表达，可能是这样：
```python
class Garbage:
    instance_count = 0
    def __init__(self):
        Garbage.instance_count += 1
        self.id = Garbage.instance_count
```
笔者这样写的目的在于自动为每个实例添加其被实例化的序号，第1个实例的id属性将会是1，第2个实例的id将会是2，以此类推。

第二，类定义体的执行是在一个特殊的命名空间中进行的，因此不能直接通过标识符来简单获得位于类名名空间中全局定义的变量。换言之，在本例的`__init__`中无法简单地跨作用域获得的`id`，而是需要通过类属性`Garbage.id`，当然这也和例子试图解释的闭包机制没有太大的关系。

**Comment by txf626** [comment]
谢谢解答
